name: core-build
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 

      - name: Configure OS
        run: |
          bash ./acore.sh install-deps
          sudo mysql -e "use mysql; update user set authentication_string="" where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      
      - name: Import db
        run: bash ./acore.sh "db-assembler" "import-all"
 
      - name: Build
        run: |
          bash ./acore.sh compiler all
