name: core-build
on: [push]

jobs:
  build:
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306
        env:
          MYSQL_USER: acore
          MYSQL_PASSWORD: acore
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 

      - name: Install deps
        run: bash ./acore.sh install-deps
      
      - name: Import db
        run: bash ./acore.sh "db-assembler" "import-all"
 
      - name: Build
        run: |
          bash ./acore.sh compiler all
