name: core-build
on: [push]

jobs:
  latest:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 

      - name: Install deps
        run: bash ./acore.sh install-deps
 
      - name: Build
        run: |
          bash ./acore.sh compiler all
